<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(TargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jint" Version="4.16.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cike.Workflow.Core\Cike.Workflow.Core.csproj" />
    <ProjectReference Include="..\Cike.Workflow.Expression\Cike.Workflow.Expressions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ClientLib\dist\lodash.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ClientLib\dist\moment.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
