<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(TargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Cike.Workflow.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Cike.Auth" Version="$(CikeVersion)" />
    <PackageReference Include="Cike.Core" Version="$(CikeVersion)" />
    <PackageReference Include="Cike.Cqrs" Version="$(CikeVersion)" />
    <PackageReference Include="Cike.EventBus.Local" Version="$(CikeVersion)" />
    <PackageReference Include="Cike.UniversalId" Version="$(CikeVersion)" />
    <PackageReference Include="Humanizer" Version="3.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cike.Workflow.Expression\Cike.Workflow.Expressions.csproj" />
  </ItemGroup>
</Project>
