<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(TargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cike.Workflow.Core\Cike.Workflow.Core.csproj" />
    <ProjectReference Include="..\Cike.Workflow.Expression\Cike.Workflow.Expressions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fluid.Core" Version="2.40.0" />
  </ItemGroup>

</Project>
