// <auto-generated />
using System;
using Cike.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cike.Workflow.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(CikeWorkflowDbContenxt))]
    partial class CikeWorkflowDbContenxtModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Cike.Workflow.Domain.Data.Entities.ActivityInstanceExecutionRecord", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ActivityNodeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("ActivityTypeVersion")
                        .HasColumnType("int");

                    b.Property<int>("AggregateFaultCount")
                        .HasColumnType("int");

                    b.Property<int?>("CallStackDepth")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasComment("CreatedAt");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy")
                        .HasComment("CreatedBy");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("HasBookmarks")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("SchedulingActivityExecutionId")
                        .HasColumnType("bigint");

                    b.Property<string>("SchedulingActivityId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long>("SchedulingWorkflowInstanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("SerializedActivityState")
                        .HasColumnType("json");

                    b.Property<string>("SerializedException")
                        .HasColumnType("json");

                    b.Property<string>("SerializedMetadata")
                        .HasColumnType("json");

                    b.Property<string>("SerializedOutputs")
                        .HasColumnType("json");

                    b.Property<string>("SerializedPayload")
                        .HasColumnType("json");

                    b.Property<string>("SerializedProperties")
                        .HasColumnType("json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("TenantId")
                        .HasMaxLength(64)
                        .HasColumnType("bigint")
                        .HasColumnName("TenantId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy")
                        .HasComment("UpdatedBy");

                    b.Property<long>("WorkflowInstanceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ActivityName");

                    b.HasIndex("ActivityType");

                    b.HasIndex("ActivityTypeVersion");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FinishedAt");

                    b.HasIndex("HasBookmarks");

                    b.HasIndex("SchedulingActivityId");

                    b.HasIndex("SchedulingWorkflowInstanceId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("ActivityType", "ActivityTypeVersion");

                    b.ToTable("ActivityInstanceExecutionRecords");
                });

            modelBuilder.Entity("Cike.Workflow.Domain.Data.Entities.BookmarkEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ActivityInstanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasComment("CreatedAt");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy")
                        .HasComment("CreatedBy");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("SerializedMetadata")
                        .HasColumnType("json");

                    b.Property<string>("SerializedPayload")
                        .HasColumnType("json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy")
                        .HasComment("UpdatedBy");

                    b.Property<long>("WorkflowInstanceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ActivityInstanceId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Hash");

                    b.HasIndex("Name");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("Name", "Hash");

                    b.HasIndex("Name", "Hash", "WorkflowInstanceId");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("Cike.Workflow.Domain.Data.Entities.BookmarkQueueItem", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ActivityInstanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("ActivityTypeName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasDefaultValue("");

                    b.Property<long>("BookmarkId")
                        .HasColumnType("bigint");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasComment("CreatedAt");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy")
                        .HasComment("CreatedBy");

                    b.Property<string>("SerializedOptions")
                        .HasColumnType("longtext");

                    b.Property<string>("StimulusHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy")
                        .HasComment("UpdatedBy");

                    b.Property<long>("WorkflowInstanceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ActivityInstanceId");

                    b.HasIndex("ActivityTypeName");

                    b.HasIndex("BookmarkId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("StimulusHash");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("BookmarkQueueItems");
                });

            modelBuilder.Entity("Cike.Workflow.Domain.Data.Entities.Folder", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasComment("CreatedAt");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy")
                        .HasComment("CreatedBy");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasComment("名称");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint")
                        .HasComment("父级目录ID");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("TenantId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy")
                        .HasComment("UpdatedBy");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ParentId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("Cike.Workflow.Domain.Data.Entities.WorkflowDefinition", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasComment("CreatedAt");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy")
                        .HasComment("CreatedBy");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasComment("描述");

                    b.Property<long>("FolderId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsReadonly")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MaterializerName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasComment("描述");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasComment("名称");

                    b.Property<string>("OriginalStringData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PublishedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified))
                        .HasComment("发布时间");

                    b.Property<Guid>("PublishedBy")
                        .HasColumnType("char(36)")
                        .HasComment("发布人ID");

                    b.Property<string>("PublishedNote")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasComment("版本说明");

                    b.Property<string>("SerializedOptions")
                        .HasColumnType("json");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("TenantId");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy")
                        .HasComment("UpdatedBy");

                    b.Property<bool>("UsableAsActivity")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FolderId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsLatest");

                    b.HasIndex("IsPublished");

                    b.HasIndex("IsSystem");

                    b.HasIndex("Name");

                    b.HasIndex("TenantId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UsableAsActivity");

                    b.HasIndex("Version");

                    b.HasIndex("DefinitionId", "Version", "IsDeleted")
                        .IsUnique();

                    b.ToTable("WorkflowDefinitions");
                });

            modelBuilder.Entity("Cike.Workflow.Domain.Data.Entities.WorkflowInstance", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasComment("CreatedAt");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy")
                        .HasComment("CreatedBy");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long>("DefinitionVersionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IncidentCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsExecuting")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasDefaultValue("");

                    b.Property<long>("ParentWorkflowInstanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("SerializedWorkflowState")
                        .HasColumnType("json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("TenantId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy")
                        .HasComment("UpdatedBy");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FinishedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsExecuting");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("TenantId", "Status");

                    b.HasIndex("TenantId", "Status", "Version");

                    b.ToTable("WorkflowInstances");
                });

            modelBuilder.Entity("Cike.Workflow.Domain.Data.Entities.Workspace", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt")
                        .HasComment("CreatedAt");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy")
                        .HasComment("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasComment("描述");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasComment("名称");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("TenantId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy")
                        .HasComment("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("TenantId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("Code", "Name");

                    b.ToTable("Workspace");
                });
#pragma warning restore 612, 618
        }
    }
}
