<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cike.Workflow.Application.Contracts\Cike.Workflow.Application.Contracts.csproj" />
    <ProjectReference Include="..\Cike.Workflow.Caching\Cike.Workflow.Caching.csproj" />
    <ProjectReference Include="..\Cike.Workflow.Domain\Cike.Workflow.Domain.csproj" />
  </ItemGroup>

</Project>
