<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(TargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cike.Cqrs" Version="$(CikeVersion)" />
    <PackageReference Include="Cike.EventBus.Local" Version="$(CikeVersion)" />
    <PackageReference Include="Cike.FluentValidation" Version="$(CikeVersion)" />
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cike.Workflow.Application.Contracts\Cike.Workflow.Application.Contracts.csproj" />
    <ProjectReference Include="..\Cike.Workflow.Domain\Cike.Workflow.Domain.csproj" />
  </ItemGroup>

</Project>
